// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARDiQy935YCuwsFpRhllhIJebTheaW8sI',
    appId: '1:399089832254:web:1173dc8028833795931c6f',
    messagingSenderId: '399089832254',
    projectId: 'safeguardher-89db9',
    authDomain: 'safeguardher-89db9.firebaseapp.com',
    storageBucket: 'safeguardher-89db9.appspot.com',
    measurementId: 'G-T30V6YX492',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlSGQHGSLypc1sTswbyFvTvoKpwk_gEBo',
    appId: '1:399089832254:android:99490d8ce4ef6046931c6f',
    messagingSenderId: '399089832254',
    projectId: 'safeguardher-89db9',
    storageBucket: 'safeguardher-89db9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqi_BrHAME_yB4qil5JukZmvTRPfHIFUs',
    appId: '1:399089832254:ios:8d81833a528cc62b931c6f',
    messagingSenderId: '399089832254',
    projectId: 'safeguardher-89db9',
    storageBucket: 'safeguardher-89db9.appspot.com',
    iosBundleId: 'com.example.safeguardher',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqi_BrHAME_yB4qil5JukZmvTRPfHIFUs',
    appId: '1:399089832254:ios:386a1680560d13da931c6f',
    messagingSenderId: '399089832254',
    projectId: 'safeguardher-89db9',
    storageBucket: 'safeguardher-89db9.appspot.com',
    iosBundleId: 'com.example.safeguardher.RunnerTests',
  );
}
